import express from "express";
import morgan from "morgan";
import cors from "cors";
import userRoutes from "./routes/user.routes";
import employeeRoutes from "./routes/employee.routes";
import roleRoutes from "./routes/role.routes";
import microServiceRoutes from "./routes/microServices.routes";
import personRoutes from "./routes/person.routes";
import customerRoutes from "./routes/customer.routes";
import serviceRoutes from "./routes/service.routes";
import reserveRoutes from "./routes/reserve.routes";
import path from 'path';
import saleRoutes from "./routes/saleReserve.routes";
import promotionRoutes from "./routes/promotion.routes";
import productRoutes from "./routes/product.routes";
import providersRoutes from "./routes/provider.routes";
import producSaleRoutes from "./routes/saleProduct.routes";
import anamnesisRoutes from "./routes/anamnesis.routes";
import dashBoardRoutes from "./routes/dashBoard.routes";
import orderEntryRoutes from "./routes/orderEntry.routes";

const app = express();
app.use(morgan("dev"));
app.use(cors({ origin: "*", methods: "GET, POST, PUT, DELETE",  allowedHeaders: ['Authorization', 'Content-Type'] }));
app.use(express.json());
app.use(userRoutes);
app.use(orderEntryRoutes);
app.use(employeeRoutes);
app.use(providersRoutes);
app.use(roleRoutes);
app.use(anamnesisRoutes);
app.use(microServiceRoutes);
app.use(dashBoardRoutes);
app.use(personRoutes);
app.use(customerRoutes);
app.use(serviceRoutes);
app.use(reserveRoutes);
app.use(saleRoutes);
app.use(promotionRoutes);
app.use(productRoutes);
app.use(producSaleRoutes);
// app.set('view engine', 'ejs');
// app.set('views', path.join(__dirname, 'extras'));

export default app;